### PR TITLE
Added Issue Menu

### PR DESCRIPTION
**Pull request by PhoneDroid**
- Added `Issues` tab menu
  - Bug report option directly links to the corresponding repo
  - Support option links to discord
  - TTT option links to TTT2 github issues
    ( Added since it seems to have been a sizable problem considering the related README note )

- Removed now uneeded bug report issue template

### CODE REVIEW

**Comment by PhoneDroid** [comment]
Btw ya might wanna:
- Disable actions
- Disable releases
- Disable packages
- Add topics

**Comment by mgetJane** [comment]
ttt2 is an unofficial addon, why should the official gmod github link to it for ttt requests?

youre supposed to just contact @svdm for ttt feature requests or bug reports that you can't make a pr for yourself

**Comment by robotboy655** [comment]
Yeah it makes no sense to link to TTT2 repo, it's completely unrelated.

**Comment by robotboy655** [comment]
The support link should also be `https://support.facepunchstudios.com/`, not the Discord server link. We can still have that, just not as "I need help with GMod", maybe as a "I want to discuss Garry's Mod" or something.

**Comment by PhoneDroid** [comment]
What is the best place for TTT (1) support in your opinion?
Sure I'll change the support thingy

**Comment by PhoneDroid** [comment]
image

**Comment by mgetJane** [comment]
> What is the best place for TTT (1) support in your opinion? 

we already discussed this in discord so i guess this is just for the record:

afaik, there isn't an actual designated place for ttt support, ttt issues, or ttt feature requests

prs for ttt will get accepted on the official gmod repo if they're backwards-compatible and if it's not stuff like game balance changes, but other than that i don't think there's an official gmod repo for ttt

bku/svdm is the authority on ttt and he seems to be responsive from what i've seen, but i haven't personally contacted him outside of getting his attention on the official r/TTT subreddit, which he still seems to read even nowadays
(do note that the subreddit is not official to facepunch!)

the official ttt website (https://www.troubleinterroristtown.com/) also links to the r/TTT subreddit
(do note that this website is not official to facepunch!)

it'd feel very silly to link to a subreddit from an official gmod github repo, but it's something i wanted to note

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
